name: todolist
#description "A simple todo list application";
services:
  db:
    image: mysql:5.7.24
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
      MYSQL_USER: todolist
      MYSQL_PASSWORD: todolist
    volumes:
      - ./todolist.sql:/docker-entrypoint-initdb.d/todolist.sql
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: bitnami/php-fpm
    depends_on:
      - db
    environment:
      PHP_FPM_LISTEN_PORT: 9000
    restart: always
  rp:
    image: nginx:stable-alpine3.20-perl
    depends_on:
      - app
    ports:
      - "12000:8080"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
    restart: always
